### ISSUE TITLE
New user and other form UX problems

### ISSUE THREAD

**Issue by javaseeds** [CampbellSoftwareSolutions/docker-osticket#24] opened 2017-04-27 17:54 UTC
Pulled image and am able to connect to existing mysql using docker compose.  Launches just fine, can log in without problem.

When I go to create new user, the resulting popups don't render properly and I can't add users correctly.

Please review attached doc and advise.
Otherwise, the container is running very well - thanks!

[osTicket_formErr-1.pdf](https://github.com/CampbellSoftwareSolutions/docker-osticket/files/962450/osTicket_formErr-1.pdf)

**Comment by martin-css** [comment] 2017-05-01 09:23
Thanks for the report. I confirm I can reproduce this issue as you describe. 

There was an issue with an older version of the image and AJAX requests that needed the nginx configuration amended to resolve. However, that certainly doesn't seem to be the case here. There are no failing network requests from the browser side. This will need some further investigation to look at the source code to find out why this isn't appearing.

I am happy to do so but am a little busy at present so it may be a little while before I get the time to do so. In the meantime, if anyone else would like to investigate, please feel free to do so and update this issue with any results.

**Comment by insanity54** [comment] 2017-08-08 18:46
I think this is a osTicket bug which occurs when osTicket is run with PHP 7.

http://osticket.com/forum/discussion/89187/cannot-create-users-or-organizations

**Comment by martin-css** [comment] 2017-08-23 14:32
Tested & can confirm that the [fix](https://github.com/osTicket/osTicket/issues/3490#issuecomment-265193495) referenced above resolves the problem.

Closing this as it appears to be a OSTicket functionality (or an unintended bug!) rather than a problem with the docker image.

**Closed by martin-css** 2017-08-23 14:32 UTC
